POST http://localhost:3333/apartment HTTP/1.1
content-type: application/json

{
  "id": "2235653265862ss",
  "size": 50,
  "numberOfRooms": 2,
  "numberOfBathrooms": 1,
  "address": "rua ramiro pimentel, avenida bem querer, 2563",
  "rent": 600
}