export const properties = [
  {
    id: 1,
    title: 'Pent House Apartment',
    location: 'Main Street, Downtown',
    price: 759,
    image:
      'https://www.lopes.com.br/blog/wp-content/uploads/2017/06/interior-2400372_1920.jpg',
    rooms: 2,
    squareMeters: 517,
    period: 'mês',
  },
  {
    id: 2,
    title: 'Cozy Studio',
    location: 'Central Avenue, Midtown',
    price: 500,
    image:
      'https://shae.com.br/wp-content/uploads/2019/07/IMG_1619-1024x682.jpg',
    rooms: 1,
    squareMeters: 350,
    period: 'mês',
  },
  {
    id: 3,
    title: 'Luxury Villa',
    location: 'Beachfront, Paradise Island',
    price: 2000,
    image: 'https://www.lopes.com.br/blog/wp-content/uploads/2015/11/i.jpg',
    rooms: 4,
    squareMeters: 800,
    period: 'mês',
  },
  {
    id: 4,
    title: 'Modern Loft',
    location: 'City Center, Urban District',
    price: 900,
    image:
      'https://imagens-revista-pro.vivadecora.com.br/uploads/2018/03/fatores-que-valorizam-o-imovel-a-arqutietura-e-uma-delas-1.jpg',
    rooms: 1,
    squareMeters: 400,
    period: 'mês',
  },
  {
    id: 5,
    title: 'Family Home',
    location: 'Quiet Neighborhood, Suburb',
    price: 1500,
    image: 'https://blog.mendesortega.com.br/wp-content/uploads/2017/08/decoracao-imoveis-alto-padrao-940x711.jpeg',
    rooms: 3,
    squareMeters: 600,
    period: 'mês',
  },
]
